### ISSUE TITLE
logging individual characters (char)

### ISSUE THREAD

**Issue by funkyshoc** [RafaGago/mini-async-log#15]
Hello the logger seems to log individual characters such as 'C' as the ASCII 67.  I think there is quite a bit of value in logging them as is such as C  

(for the native type char)

00000000000.019507570 [err_] message 37, char ('C') = 67

If there is no way to do so, do you think this would be easy to change?

**Comment by RafaGago** [comment]
Well it's just adding an extra modifier:

https://github.com/RafaGago/mini-async-log/blob/master/src/mal_log/log_writer.hpp#L318

To update the compile time validators:

https://github.com/RafaGago/mini-async-log/blob/master/include/mal_log/compile_format_validator.hpp#L92

And to update the runtime validator:

**Comment by RafaGago** [comment]
It turned out to be easy to fix:

https://github.com/RafaGago/mini-async-log/commit/8a5ef6a33352fc06ade42ed404f919821b1a4125

**Comment by funkyshoc** [comment]
Great!
