### ISSUE TITLE
Can I add new log levels?

### ISSUE THREAD

**Issue by ruipacheco** [RafaGago/mini-async-log#9]
spdlog has trace support which is great for development - it's only included if DEBUG is enabled or a specific flag is passed at compile time. Do you support the same?

**Comment by RafaGago** [comment]
There already some lot of log levels in place. Check the sev structure.

https://github.com/RafaGago/mini-async-log/blob/master/include/mal_log/frontend_types.hpp

They are (and will be) static, as they are serialized to a memory blob with no more avaliable bytes. I think that you should have enough. There are 6 log levels (0 to 5).

BTW, you use the macros with the log level, e.g.

> log_debug("my data is {}", data);

You can add debug printouts freely in your code, as you can remove these entries at compile time by e.g. defining the preprocessor variable "MAL_STRIP_LOG_DEBUG". This will remove them (and some of the template code bloat).

"MAL_STRIP_LOG_SEVERITY 0" will remove the logging log level at compile time, "MAL_STRIP_LOG_SEVERITY 1" the debug and trace, etc...
